### ISSUE TITLE
Error using konsta with nuxt3

### ISSUE THREAD

**Issue by mortegro** [konstaui/konsta#54]
I can't get konsta to work with nuxt 3.0.0-rc3.

In dev-mode everything is fine, but when i build the app with "nuxt build" I get an Error: 
  TypeError: Cannot read properties of null (reading 'isCE') 

Can someone please help me to fix this?

**Comment by shiftlabs1** [comment]
@mortegro  how did you even get it working in Dev mode. It doesn't seem to work. Css does not get applied . i have tried with nuxt 3.0.0-rc3 and nuxt 3.0.0-rc4

**Comment by shiftlabs1** [comment]
@nolimits4web  can you please create a Nuxt3 starter of this library, on stackblitz for e.g as part of the documentation. It doesn't seem to work with nuxt3. I do not think konstaconfig or any of the internal plugins is being picked up

**Comment by nolimits4web** [comment]
Here is the repo where it works https://github.com/konstaui/konsta-nuxt3-starter

In prod mode i also see that `isCE` error, will check that but i guess it could happen because of Konsta package was built with different Vue version rather than Vue version used in Nuxt. Probably konsta-vue package needs to delivery just plain `.vue` files

**Comment by shiftlabs1** [comment]
Plain .vue files will be very helpful . I will look at the starter. Thanks so much @nolimits4web

**Comment by nolimits4web** [comment]
fixed in 0.11.0, check/fork starter repo, works both dev and prod builds

**Comment by mortegro** [comment]
Thanks a lot. The fixed version works like a charm!
